---
spring:
  profiles: default
  application: 
    name: ws_discovery
server:
  port: 8081


eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/

---
spring:
  profiles: peer1
  application: 
    name: ws_discovery
server:
  port: 8081


eureka:
  instance:
    hostname: ${spring.application.name}-${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/,http://localhost:8083/eureka/

---
spring:
  profiles: peer2
  application: 
    name: ws_discovery
server:
  port: 8082


eureka:
  instance:
    hostname: ${spring.application.name}-${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/,http://localhost:8083/eureka/

---
spring:
  profiles: peer3
  application: 
    name: ws_discovery
server:
  port: 8083


eureka:
  instance:
    hostname: ${spring.application.name}-${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/,http://localhost:8082/eureka/